### ISSUE TITLE
Find a replacement for Elm-package

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#130]

**Comment by OvermindDL1** [comment]
What are you wanting the replacement to do that elm-package cannot do already?

**Comment by wende** [comment]
@OvermindDL1 The package didn't get official backup from elm-core team and since the package is not an official part of Elm I think there might be a need in future to move away from Elm's package manager if they decide that they're not willing to host libraries written for Elmchemy explicitly.

Plus also elm-package allows only for publishing packages written 100% in Elm or with JavaScript ports if they pass the review. And I'm pretty sure that native Elixir code won't pass it 😁 

So there will be a need of a package manager without these limitations.
I'm assuming a nice wrapper around both elm-package and hex pm could be able to have both the usability of current system and a nice auto-generated documentation of packages shared to `package.elm-lang` 

Also a nice thing as a bonus would be that we could use `Native` modules instead of `ffi`, because it wouldn't be forbidden as in Elm-package it is right now

**Comment by wende** [comment]
One thing that might be problematic is how to download existing Elm libraries that work well in Elmchemy (those that don't use neither Native nor Ports). Like `list-extras` or `evancz/lens`

Worst case scenario they could be included using github link since Hex PM allows that

**Comment by MartinKavik** [comment]
Hi, @wende try to look at [gdotdesign/elm-github-install](https://github.com/gdotdesign/elm-github-install) for some inspiration. I used it in my small experiment ([MartinKavik/tachyons-elm-ui-example](https://github.com/MartinKavik/tachyons-elm-ui-example)) and it seems to be quite reliable.

Btw thanks for this repo, it's a great idea. I like Elixir, but I like to see only compile-time errors more.

**Comment by wende** [comment]
@MartinKavik That's a great idea!
I wasn't aware of it's existence. It shouldn't be hard to integrate that into Elmchemy binary file

**Comment by wende** [comment]
@MartinKavik huge thanks for pointing us towards that repo. It turned out to be our ultimate solution! 👍
