### ISSUE TITLE
Discuss a way to distinguish compiled output files in a project from regular elixir files

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#134]
There should be a way to distinguish between files that are an output of E[lm/x]chemy from regular Elixir file. Main reason being an ability to exclude generated files from source control

**Suggestion 1 - A separate directory:**

Pros:
  - Simple configuration
  - clear distinction
  - one command to remove all generated files

Cons:
  - Duplicated tree of directories in case of multi-nested folders
  - Hard to reason about (had to look into three exact same directory trees when looking for a bug)

**Suggestion 2 - `my_file.exchemy.ex`**

Pros:
  - Still can be excluded using simple wildcard
  - Less directories == nicer project structure

Cons:
  - Can cause problems in dumber text editors (?)
  - Removing all generated files requires a `find -delete` command or a custom command instead of simple `rm -rf dir`

**Comment by OvermindDL1** [comment]
> my_file.exchemy.ex

I vote for this.  Although having it dump to somewhere in `_build` makes sense too, like protocol output.  Maybe make it an option?
