### ISSUE TITLE
Add syntax for module atoms

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#18]
Add:

## Example:
```elm
mod "Some.Module"
```
->
```elixir
Some.Module
```

**Comment by Baransu** [comment]
I'm not sure if I understand it correctly. Can you explain it? What is use case for that?

**Comment by wende** [comment]
@Baransu Right now every uppercase type changes to snake case atoms:
`Type` -> `:type`. But sometimes in rare cases there is a need to express a module atom like `Module`, for example when passing a name to a process.
In Elixir module atoms are still regular atoms but they are:
1) Resolved through aliases
2) Prepended with `Elixir.`

**Comment by wende** [comment]
Closed in favour of #140
