### ISSUE TITLE
Typing failure

### ISSUE THREAD

**Issue by OvermindDL1** [wende/elmchemy#35]
So, there appears to be a slight typing failure.  :-)

## Example:
```elm
module Stack exposing (..)

type alias TestRecord =
  { int : int
  , float : float
  }

blah : TestRecord
blah =
  42

blorp =
  blah.x
```
->
```elixir
# Compiled using Elmchemy v0.0.17
defmodule Stack do
  use Elmchemy

  @spec blah :: %{int: any, float: any}
  curry blah/0
  def blah() do
    42
  end

  curry blorp/0
  def blorp() do
    blah.x
  end

end
```

As an example, my MLElixir project (which puts a strongly-typed ML face on Elixir, it is not a released project, just something I screw around with for fun, its errors are also very low level and not prettied up at all) compiles the similar code as the above Elm:
```elixir
iex> import MLElixir
MLElixir
iex> defmlmodule Stack do
...>   type test_record = %{
...>     int: integer,
...>     float: float,
...>   }
...>
...>   let blah | test_record = 42
...>
...>   let blorp = blah.x
...> end
```
Gives this:
```elixir
** (throw) {:NO_TYPE_RESOLUTION, %TypedElixir.Type.Const{const: :integer, meta: %{values: '*'}}, %TypedElixir.Type.Const{const: :integer, meta: %{values: '*'}}, %TypedElixir.Type.Record{labels: [int: %TypedElixir.Type.Const{const: :integer, meta: %{}}, float: %TypedElixir.Type.Const{const: :float, meta: %{}}], meta: %{}}}
```
Which is entirely expected, but currently the above elm code is working in elmchamy when it absolutely should not.

Looking forward to this being developed out.  :-)

**Comment by wende** [comment]
As far as I'm concerned it's not a code that would pass through Elm-make. 
Right now the web compiler only checks AST and it doesn't type-check, while command-line version does both.
So even though you are able to write complete nonsense in the browser like:
<img width="1401" alt="screen shot 2017-04-28 at 17 43 36" src="https://cloud.githubusercontent.com/assets/4634386/25536206/3be6ffc0-2c3a-11e7-919a-cdbcc58bdf13.png">

It certainly wouldn't allow that if you were compiling a real file.

Given that premise your code would fail at type checking time, rather then parsing time.

<img width="684" alt="screen shot 2017-04-28 at 17 47 00" src="https://cloud.githubusercontent.com/assets/4634386/25536327/b5ee75a0-2c3a-11e7-81fd-3a9a85f36caf.png">

It should although work for

```elm
type alias TestRecord =
  { int : Int
  , float : Float
  }
blah : TestRecord
blah =
  TestRecord 42 0.0
```
which should produce
```elixir
@type test_record %{int: integer, float: float}
@spec blah() :: test_record
blah =
  %{int: 42, float: 0.0}
```

Which is an ongoing issue to solve. But type aliases are still very early stage.

Correct me If I got something wrong from your issue.
Thank you for interest!

**Comment by wende** [comment]
Fixed in 9dca53b

**Comment by OvermindDL1** [comment]
Ahh, so you require elm-make then, it is not an optional dependency?

**Comment by wende** [comment]
@OvermindDL1 It is optional, if you don't want your types to be checked ;)

**Comment by OvermindDL1** [comment]
> @OvermindDL1 It is optional, if you don't want your types to be checked ;)

Seems point defeating to not want that in my opinion.  ^.^
