### ISSUE TITLE
Implement `Let` block

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#36]
Add:
Let
## Example:
```elm
let 
  a = 1
in
  a * 2
```
->
```elixir
a = 1
a * 2
```

**Comment by net** [comment]
Is there a need for `let` instead of simply writing

```elixir
a = 1
a * 2
```

?

**Comment by OvermindDL1** [comment]
> Is there a need for let instead of simply writing

Beside that it is not valid elm?  It allows you to define recursive structures too.

**Comment by wende** [comment]
Exactly. So far we're trying to be syntactically idiomatic to Elm. When we succeed to copy the whole language we might discuss some changes. But it's definitely not a time for that yet :) 

Plus having `let... in` has a very important implication which is being consistent about functions being only one expression

**Comment by net** [comment]
> It allows you to define recursive structures too.

Could you elaborate on this @OvermindDL1?

**Comment by net** [comment]
> Plus having let... in has a very important implication which is being consistent about functions being only one expression

Assignment is not an expression in Elm.

**Comment by OvermindDL1** [comment]
> Could you elaborate on this @OvermindDL1?

Some valid elm, you can create inline mutually recursive functions and calls and such.
```elm
import Html exposing (text)

main =
  let
    r = c 1
    a b = 21 * b
    c d = a (d+1)
  in text (toString r)
```

I still prefer the OCaml method though, much more clear and redefinable...

**Comment by net** [comment]
You could still achieve that without the `let` syntax.

```
import Html exposing (text)

main =
  r = c 1
  a b = 21 * b
  c d = a (d+1)

  text (toString r)
```

**Comment by OvermindDL1** [comment]
The purpose is to allow rebinding as well (this is not valid elm because elm is a bit stupid in how it does a lot of things):
```elm
import Html exposing (text)

main =
  let
    r = c 1
    a b = 21 * b
    c d = a (d+1) in
  let r = r + 1 in
  text (toString r)
```
In addition to controlling scoping and more things.

Plus, it does not matter, it is still not valid elm to leave the `let` out.  ;-)

**Comment by wende** [comment]
> Assignment is not an expression in Elm.

@net Exactly. But the `let..in` block is

**Comment by net** [comment]
@OvermindDL1 Is rebinding in an expression _really_ that important? Many would argue that rebinding only causes confusion. Pick better variable names instead.

Scoping is entirely possible with the non-`let` syntax.

**Comment by net** [comment]
@wende Right, so allowing assignments before an expression does not violate the one-expression-per-function rule.

**Comment by OvermindDL1** [comment]
> @wende Right, so allowing assignments before an expression does not violate the one-expression-per-function rule.

Unless you are getting into whitespace sensitivity (ew) then it becomes ambiguous:
```elm
  a = 4
  b = 4 + a
  b + 6
```
Unless the language is whitespace sensitive (big ew) it is parsed like:
```elm
  (a = 4) (b = (4 + (a b) + 6)
```
The `let ... in ...` defines bounds.

But still, it is a moot point, elm does not allow it.  ;-)

**Comment by wende** [comment]
@OvermindDL1 
Elm is a little bit whitespace sensitive when it comes to case branches and function calls.
For example

```
...
Something -> 
  fun 
     a
     b
     c
SomethingElse b c ->
...
```
You can't really know where fun ends, and next case starts. It's a big issue to solve for us right now #40 and it's gonna be really hard because of whitespace sensitivity.
So I definitely preach to your ew

**Comment by OvermindDL1** [comment]
> Elm is a little bit whitespace sensitive when it comes to case branches and function calls.

I know, it endlessly bugs me.  ^.^;

Honestly I'd say you should write a new backend for OCaml that compiles to Elixir instead.  ^.^
I've been wanting to do that, but so very much lacking on time...
