### ISSUE TITLE
Add support for module attributes

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#4]
Example
```elm
a = 2
```
->
```eixir
@a 2
```

**Comment by Baransu** [comment]
Should this be done when right side is primitive only?

**Comment by wende** [comment]
@Baransu Not particularly. It can be any expression.
For example in Elixir
```
@port = "1234" |> String.to_integer
```
Is a valid code
And so should be
```elm
port = "1234" |> String.toInt
```
But obviously we should denote somehow that `@a \= a`

**Comment by Baransu** [comment]
So in Elixir `@a` is a const pasted into place where `@a` is used during compilation, right? So how do you want to distinguish when to convert Elm function to module attribute?

**Comment by wende** [comment]
Yes. Module attributes are calculated during compilation, and then pasted in every place they're used. 
There probably should be some naming convention for them. 
Like `a_name` -> `@name`.
But unfortunately Elm removed option to have variables names starting with any symbol.

**Comment by Baransu** [comment]
We should add  `@doc` to blacklist for module attributes since we handle it by doc comments.

**Comment by Baransu** [comment]
Do we need it at all? We're writing Elm so simple function would work. It will be executed during runtime so we will have performance loss but after all module attributes are not every heavy performance wise.

**Comment by wende** [comment]
I think it might be true. I don't think there is any sense of using it other than: `@a 1` being shorter than `defp a(), do: 1` but with `a = 1` we don't have that problem at all. I think you might be right @Baransu
