### ISSUE TITLE
Add support for empty tuple `()`

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#44]
Add:

## Example:
```elm
()
```
->
```elixir
{}
```

**Comment by Baransu** [comment]
I'm waiting to [this](https://github.com/Bogdanp/elm-ast/pull/29) getting merged so I can work on that.

**Comment by wende** [comment]
It could also be discussed to be used as Haskell does it instead to signalise () as a side effect, and translate it to `@spec :: no_return`

**Comment by wende** [comment]
But then it would be inconsistent in terms of

```
@spec fun :: no_return
def fun(), do: {}
```
So we need to decide either to do it `no_return` and forbid in code or allow in both and make an empty tuple
