### ISSUE TITLE
Add support for function documentation 

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#45]
Add:

## Example:
```elm
{-| my function that is awesome -}
function : Awesome
function = Awesome
```
->
```elixir
@doc "my function that is awesome"
@spec function :: :awesome
def function(), do: :awesome
```

This is an AST job because elm-ast sees no difference between block and regular comments

**Comment by Baransu** [comment]
And `{- example function -}` will cause crash because of our `{- ex -}`

**Comment by Baransu** [comment]
We should stick to Elm's convention to that `{-| ... -}`

http://package.elm-lang.org/help/documentation-format

**Comment by wende** [comment]
Corrected. No AST label then :+1:
