### ISSUE TITLE
Support custom operators from Elm to Elixir

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#56]
Add:

## Example:
```elm
(~~) a b = a ++ b

a ~~ b
```
->
```elixir
curry _dashdash/2
def _dashdash(a, b) do
  a + b
end

_dashdash(a, b)
```

**Comment by Baransu** [comment]
So we should add some dictionary to context and store different function names when name starts with parentheses.

**Comment by wende** [comment]
Yup. Pretty much yes

**Comment by wende** [comment]
And actually that's exactly what elm does into javascript
